//Posts
GET http://localhost:3001/api/posts

###

GET http://localhost:3001/api/posts/6082e658d153700a81ce5553

###

POST http://localhost:3001/api/posts
Content-Type: application/json

{   
    "title": "New Post",
    "author": "User Name",
    "date": "2021-04-20",
    "text": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque arcu augue, euismod at viverra ac, facilisis ac ante. Vivamus nunc erat, rutrum sit amet neque vitae, luctus aliquet ipsum. Sed dapibus facilisis feugiat. Suspendisse vestibulum at elit et sodales. Praesent leo odio, pulvinar eget ex in, fringilla varius sapien. Aliquam vitae mi in libero efficitur consectetur. Interdum et malesuada fames ac ante ipsum primis in faucibus. Proin augue erat, faucibus quis enim nec, vestibulum faucibus mauris. Suspendisse sagittis massa ut nibh blandit dapibus. In tincidunt quis magna non congue.",
    "imageUrl": "https://github.com/stonetwix/user-based-content/blob/main/client/src/assets/travel3.png?raw=true"
}

###

PUT http://localhost:3001/api/posts/6082e658d153700a81ce5553
Content-Type: application/json

{
    "title": "Edited Post",
    "author": "User Name",
    "date": "2021-04-20",
    "text": "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    "imageUrl": "https://github.com/stonetwix/user-based-content/blob/main/client/src/assets/travel1.png?raw=true"
}

###

DELETE http://localhost:3001/api/posts/60840a153789c57270f81cb5

###

//Users
GET http://localhost:3001/api/users

###

GET http://localhost:3001/api/users/6086b7432a9d1282e1fbbc64

###

POST http://localhost:3001/api/users
Content-Type: application/json

{   
    "username": "New User",
    "email": "info@hejhej1.com",
    "password": "123456"
}

###

POST http://localhost:3001/api/login
Content-Type: application/json

{   
    "email": "info@hejhej1.com",
    "password": "123456"
}

###

PUT http://localhost:3001/api/users/6086ba4d2a9d1282e1fbbc66
Content-Type: application/json

{
    "username": "Edited user",
    "email": "info@hejhej2.com",
    "role": "admin",
    "password": "123456"
}

###

DELETE http://localhost:3001/api/users/608285c1f1cf40287c5a9a80

###

DELETE http://localhost:3001/api/logout